apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-kube.yaml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
spec:
  ports:
  - port: 3307
    targetPort: 3306
  selector:
    io.kompose.service: mysqldb
status:
  loadBalancer: {}
