apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
          - name: DB_HOST
            value: localhost
          - name: MYSQLDB_DATABASE
            value: test_db
          - name: MYSQLDB_DOCKER_PORT
            value: "3306"
          - name: MYSQLDB_LOCAL_PORT
            value: "3307"
          - name: MYSQLDB_ROOT_PASSWORD
            value: "123456"
          - name: MYSQLDB_USER
            value: root
          - name: MYSQL_DATABASE
            value: test_db
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
          - name: NODE_DOCKER_PORT
            value: "8080"
          - name: NODE_LOCAL_PORT
            value: "8080"
        image: mysql:5.7
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim