apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-kube.yaml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysqldb
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: localhost
        - name: MYSQLDB_DATABASE
          value: test_db
        - name: MYSQLDB_DOCKER_PORT
          value: "3306"
        - name: MYSQLDB_LOCAL_PORT
          value: "3307"
        - name: MYSQLDB_ROOT_PASSWORD
          value: "123456"
        - name: MYSQLDB_USER
          value: root
        - name: MYSQL_DATABASE
          value: test_db
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: NODE_DOCKER_PORT
          value: "8080"
        - name: NODE_LOCAL_PORT
          value: "8080"
        image: mysql:5.7
        name: mysqldb
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db
      restartPolicy: Always
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: db
status: {}
